ALTER TABLE playlists ADD COLUMN is_system INTEGER DEFAULT 0;
ALTER TABLE playlists ADD COLUMN is_liked INTEGER DEFAULT 0;
ALTER TABLE playlists ADD COLUMN pinned INTEGER DEFAULT 0;
ALTER TABLE playlists ADD COLUMN pinned_at TEXT;
